name: Matrix Build Example

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Debug repository contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing all files:"
          ls -R
        # This step helps you see what files are in your repository

      - name: Show Python version
        run: python --version
        # Confirms which Python version is being used

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        # Installs pytest directly since there's no requirements.txt

      - name: Run tests
        run: |
          pytest
        # Runs pytest to execute your tests